#define addr_kernel_48 0x800
#define addr_transport_buttons 0x880
#define addr_transport_direction 0x897
#define addr_right_line 0x94c
#define addr_left_line 0x980
#define addr_pick_continue 0x9c2
#define addr_main_start 0xa00
#define addr_aud_bank_setup 0xa0c
#define addr_tg0 0xa24
#define addr_title_again 0xa3b
#define addr_end_lines 0xa80
#define addr_end_lines_audio 0xaa1
#define addr_set_overscan_size 0xaad
#define addr_set_vblank_size 0xac3
#define addr_pick_transport 0xacc
#define addr_last_audio 0xacf
#define addr_wait_lines 0xad4
#define addr_transport_done1 0xae7
#define addr_draw_title 0xb00
#define addr_title_loop 0xb50
#define addr_black_bar 0xb52
#define addr_animate_bar1 0xb58
#define addr_animate_bar_again1 0xb5a
#define addr_animate_dex1 0xb65
#define addr_audio_bank 0xb80
#define addr_reset_loop 0xbfa
